-- Custom Hyprland Keybindings

-- Unbind default workspace switches to allow Keyd Caps+Number control
for workspace = 1, 10 do
  local key = "code:" .. tostring(workspace + 9)
  hl.unbind("SUPER + " .. key)
  hl.unbind("SUPER + SHIFT + " .. key)
end

-- Unbind defaults that we are overriding
hl.unbind("SUPER + RETURN")
hl.unbind("SUPER + ALT + RETURN")
hl.unbind("SUPER + SHIFT + RETURN")
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + ALT + SHIFT + F")
hl.unbind("SUPER + SHIFT + B")
hl.unbind("SUPER + SHIFT + ALT + B")
hl.unbind("SUPER + SHIFT + N")
hl.unbind("SUPER + SHIFT + K")
hl.unbind("SUPER + SHIFT + I")
hl.unbind("SUPER + F")
hl.unbind("SUPER + T")
hl.unbind("SUPER + B")
hl.unbind("SUPER + M")
hl.unbind("SUPER + N")
hl.unbind("SUPER + D")
hl.unbind("SUPER + O")
hl.unbind("SUPER + G")
hl.unbind("SUPER + L")
hl.unbind("SUPER + W")
hl.unbind("SUPER + S")
hl.unbind("SUPER + P")
hl.unbind("SUPER + J")
hl.unbind("SUPER + K")
hl.unbind("SUPER + LEFT")
hl.unbind("SUPER + RIGHT")
hl.unbind("SUPER + UP")
hl.unbind("SUPER + DOWN")
hl.unbind("SUPER + SPACE")
hl.unbind("ALT + TAB")
hl.unbind("PRINT")

-- Application launch bindings
o.bind("SUPER + RETURN", "Terminal", "uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\"")
o.bind("SUPER + ALT + RETURN", "Tmux", "uwsm-app -- xdg-terminal-exec --dir=\"$(omarchy-cmd-terminal-cwd)\" bash -c \"tmux attach || tmux new -s Work\"")
o.bind("SUPER + SHIFT + RETURN", "Browser", "omarchy-launch-browser")
o.bind("SUPER + F", "File manager", "uwsm-app -- nautilus --new-window")
o.bind("SUPER + SHIFT + F", "File manager", "uwsm-app -- nautilus --new-window")
o.bind("SUPER + ALT + SHIFT + F", "File manager (cwd)", "uwsm-app -- nautilus --new-window \"$(omarchy-cmd-terminal-cwd)\"")
o.bind("SUPER + T", "Activity", "omarchy-launch-tui btop")
o.bind("SUPER + B", "Browser", "omarchy-launch-browser")
o.bind("SUPER + SHIFT + B", "Browser", "omarchy-launch-browser")
o.bind("SUPER + SHIFT + ALT + B", "Browser (private)", "omarchy-launch-browser --private")
o.bind("SUPER + M", "Music", "omarchy-launch-or-focus spotify")
o.bind("SUPER + SHIFT + M", "Music", "omarchy-launch-or-focus spotify")
o.bind("SUPER + SHIFT + ALT + M", "Music TUI", "omarchy-launch-or-focus-tui cliamp")
o.bind("SUPER + N", "Editor", "omarchy-launch-editor")
o.bind("SUPER + SHIFT + N", "Editor", "omarchy-launch-editor")
o.bind("SUPER + D", "Docker", "omarchy-launch-tui lazydocker")
o.bind("SUPER + SHIFT + D", "Docker", "omarchy-launch-tui lazydocker")
o.bind("SUPER + SHIFT + G", "Signal", "omarchy-launch-or-focus ^signal$ \"uwsm-app -- signal-desktop\"")
o.bind("SUPER + SHIFT + O", "Obsidian", "omarchy-launch-or-focus ^obsidian$ \"uwsm-app -- obsidian\"")
o.bind("SUPER + SHIFT + W", "Typora", "uwsm-app -- typora --enable-wayland-ime")
o.bind("SUPER + SHIFT + SLASH", "Passwords", "uwsm-app -- 1password")

-- Web Apps
o.bind("SUPER + A", "Gemini", "omarchy-launch-webapp \"https://gemini.google.com\"")
o.bind("SUPER + SHIFT + A", "Claude", "omarchy-launch-webapp \"https://claude.ai\"")
o.bind("SUPER + SHIFT + ALT + A", "Grok", "omarchy-launch-webapp \"https://grok.com\"")
o.bind("SUPER + Y", "YouTube", "omarchy-launch-or-focus-webapp YouTube \"https://youtube.com/\"")
o.bind("SUPER + SHIFT + Y", "YouTube", "omarchy-launch-webapp \"https://youtube.com/\"")
o.bind("SUPER + SHIFT + C", "Calendar", "omarchy-launch-webapp \"https://app.hey.com/calendar/weeks/\"")
o.bind("SUPER + SHIFT + E", "Email", "omarchy-launch-webapp \"https://app.hey.com\"")
o.bind("SUPER + SHIFT + ALT + G", "WhatsApp", "omarchy-launch-or-focus-webapp WhatsApp \"https://web.whatsapp.com/\"")
o.bind("SUPER + SHIFT + CTRL + G", "Google Messages", "omarchy-launch-or-focus-webapp \"Google Messages\" \"https://messages.google.com/web/conversations\"")
o.bind("SUPER + SHIFT + P", "Google Photos", "omarchy-launch-or-focus-webapp \"Google Photos\" \"https://photos.google.com/\"")
o.bind("SUPER + SHIFT + X", "X", "omarchy-launch-webapp \"https://x.com/\"")
o.bind("SUPER + SHIFT + ALT + X", "X Post", "omarchy-launch-webapp \"https://x.com/compose/post\"")

-- System & Utilities
o.bind("ALT + SPACE", "Launch apps", "omarchy-menu toggle")
o.bind("SUPER + G", "Power Mode", "omarchy-menu power")
o.bind("SUPER + O", "Pop window out", "omarchy-hyprland-window-pop")
o.bind("SUPER + P", "Toggle workspace layout", "omarchy-hyprland-workspace-layout-toggle")
o.bind("SUPER + SPACE", "Toggle layout (scrolling/dwindle)", "~/.config/hypr/toggle-layout.sh")
o.bind("SUPER + SHIFT + K", "Show key bindings", "omarchy-menu-keybindings")
o.bind("ALT + TAB", "Find windows", "~/.config/scripts/find-open-window.sh")
o.bind("SUPER + SHIFT + I", "Toggle idle lock", "omarchy-toggle-idle")

-- Navigation & Window Focus
o.bind("SUPER + H", "Focus left", hl.dsp.focus({ direction = "l" }))
o.bind("SUPER + J", "Focus down", hl.dsp.focus({ direction = "d" }))
o.bind("SUPER + K", "Focus up", hl.dsp.focus({ direction = "u" }))
o.bind("SUPER + L", "Focus right", hl.dsp.focus({ direction = "r" }))
o.bind("SUPER + X", "Focus left", hl.dsp.focus({ direction = "l" }))
o.bind("SUPER + C", "Focus right", hl.dsp.focus({ direction = "r" }))
o.bind("SUPER + LEFT", "Move window left", hl.dsp.window.move({ direction = "l" }))
o.bind("SUPER + RIGHT", "Move window right", hl.dsp.window.move({ direction = "r" }))
o.bind("SUPER + UP", "Move window up", hl.dsp.window.move({ direction = "u" }))
o.bind("SUPER + DOWN", "Move window down", hl.dsp.window.move({ direction = "d" }))

-- Keyd Capslock MEH bindings (CTRL + ALT + SHIFT)
for ws = 1, 9 do
  o.bind("CTRL + ALT + SHIFT + " .. ws, "Switch to workspace " .. ws, hl.dsp.focus({ workspace = tostring(ws) }))
  o.bind("ALT + SHIFT + " .. ws, "Move window to workspace " .. ws, hl.dsp.window.move({ workspace = tostring(ws) }))
end
o.bind("ALT + SHIFT + 0", "Move window to workspace 10", hl.dsp.window.move({ workspace = "10" }))

o.bind("CTRL + ALT + SHIFT + W", "Close active window", hl.dsp.window.close())
o.bind("CTRL + ALT + SHIFT + X", "Switch to workspace 6", hl.dsp.focus({ workspace = "6" }))
o.bind("CTRL + ALT + SHIFT + R", "Toggle scratchpad", hl.dsp.workspace.toggle_special("scratchpad"))
o.bind("SHIFT + ALT + R", "Move window to scratchpad", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))

-- Keyd Utilities
o.bind("CTRL + ALT + SHIFT + S", "Screenshot", "omarchy-capture-screenshot smart copy")
o.bind("PRINT", "Screenshot Editor", "~/.config/scripts/edit-clipboard-with-satty.sh")
o.bind("CTRL + ALT + SHIFT + D", "Paste Smart", "~/.config/scripts/paste-clipboard.sh")
o.bind("CTRL + ALT + SHIFT + F", "Fullscreen", hl.dsp.window.fullscreen({ mode = "fullscreen" }))
o.bind("CTRL + ALT + SHIFT + SPACE", "Clipboard Manager", "omarchy-shell shell toggle omarchy.clipboard")
o.bind("CTRL + ALT + SHIFT + T", "Toggle floating", hl.dsp.window.float({ action = "toggle" }))
o.bind("CTRL + ALT + SHIFT + G", "Toggle window grouping", hl.dsp.group.toggle())
o.bind("CTRL + ALT + SHIFT + B", "Toggle Trackpad", "~/.config/scripts/toggle-trackpad.sh")
o.bind("CTRL + ALT + SHIFT + E", "Toggle Voice Dictation", "~/.config/scripts/groq-dictate.sh")
o.bind("ALT + SHIFT + X", "Move all windows to primary", "~/.config/scripts/move-all-windows-to-primary-monitor.sh")

-- Shortcut chords for copy/paste/select-all
o.bind("CTRL + ALT + SHIFT + C", "Copy shortcut", function()
  hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "Insert", state = "down" }))
  hl.timer(function()
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "Insert", state = "up" }))
  end, { timeout = 50, type = "oneshot" })
end)

o.bind("CTRL + ALT + SHIFT + V", "Paste shortcut", function()
  hl.dispatch(hl.dsp.send_key_state({ mods = "SHIFT", key = "Insert", state = "down" }))
  hl.timer(function()
    hl.dispatch(hl.dsp.send_key_state({ mods = "SHIFT", key = "Insert", state = "up" }))
  end, { timeout = 50, type = "oneshot" })
end)

o.bind("CTRL + ALT + SHIFT + A", "Select all shortcut", function()
  hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "a", state = "down" }))
  hl.timer(function()
    hl.dispatch(hl.dsp.send_key_state({ mods = "CTRL", key = "a", state = "up" }))
  end, { timeout = 50, type = "oneshot" })
end)
